//Datos para tabla pais

insert into pais
values (null, 'Argentina'),
(null, 'Chile'),
(null, 'Brasil'),
(null, 'Paraguay'),
(null, 'Perú');


//Datos para tabla provincia

insert into provincia
values (null, 1, 'Ciudad Autónoma de Buenos Aires'),
(null, 1, 'Buenos Aires'),
(null, 1, 'Catamarca'),
(null, 1, 'Chaco'),
(null, 1, 'Chubut'),
(null, 1, 'Córdoba'),
(null, 1, 'Corrientes'),
(null, 1, 'Entre Ríos'),
(null, 1, 'Formosa'),
(null, 1, 'Jujuy'),
(null, 1, 'La Pampa'),
(null, 1, 'La Rioja'),
(null, 1, 'Mendoza'),
(null, 1, 'Misiones'),
(null, 1, 'Neuquén'),
(null, 1, 'Río Negro'),
(null, 1, 'Salta'),
(null, 1, 'San Juan'),
(null, 1, 'San Luis'),
(null, 1, 'Santa Cruz'),
(null, 1, 'Santa Fe'),
(null, 1, 'Santtiago del Estero'),
(null, 1, 'Tierra del Fuego, Antártida e Islas del Atlántico Sur'),
(null, 1, 'Tucumán');


//Datos para tabla localidad

insert into localidad
values (null, 1, 'Agronomía'),
(null, 1, 'Almagro'),
(null, 1, 'Balvanera'),
(null, 1, 'Barracas'),
(null, 1, 'Belgrano'),
(null, 1, 'Boedo'),
(null, 1, 'Caballito'),
(null, 1, 'Chacarita'),
(null, 1, 'Coghlan'),
(null, 1, 'Colegiales'),
(null, 1, 'Constitución'),
(null, 1, 'Flores'),
(null, 1, 'Floresta'),
(null, 1, 'La Boca'),
(null, 1, 'La Paternal'),
(null, 1, 'Liniers'),
(null, 1, 'Mataderos'),
(null, 1, 'Monte Castro'),
(null, 1, 'Monserrat'),
(null, 1, 'Nueva Pompeya'),
(null, 1, 'Núñez'),
(null, 1, 'Palermo'),
(null, 1, 'Parque Avellaneda'),
(null, 1, 'Parque Chacabuco'),
(null, 1, 'Parque Chas'),
(null, 1, 'Parque Patricios'),
(null, 1, 'Puerto Madero'),
(null, 1, 'Recoleta'),
(null, 1, 'Retiro'),
(null, 1, 'Saavedra'),
(null, 1, 'San Cristóbal'),
(null, 1, 'San Nicolás'),
(null, 1, 'San Telmo'),
(null, 1, 'Vélez Sársfield'),
(null, 1, 'Versalles'),
(null, 1, 'Villa Crespo'),
(null, 1, 'Villa del Parque'),
(null, 1, 'Villa Devoto'),
(null, 1, 'Villa General Mitre'),
(null, 1, 'Villa Lugano'),
(null, 1, 'Villa Luro'),
(null, 1, 'Villa Ortúzar'),
(null, 1, 'Villa Pueyrredón'),
(null, 1, 'Villa Real'),
(null, 1, 'Villa Riachuelo'),
(null, 1, 'Villa Santa Rita'),
(null, 1, 'Villa Soldati'),
(null, 1, 'Villa Urquiza');
